mission-apprentissage/api-apprentissage

- ui/app/mentions-legales/components/MentionLegales.tsx
MAJ du contenu de la page Mentions légales
Cf : https://www.notion.so/mission-apprentissage/Mentions-l-gales-cdf5bb038f6f490caeddeb89eff0e9d6?pvs=4
> feat(ui): update mention legales content

- ui/app/cgu/components/Cgu.tsx
MAJ du contenu de la page CGU.
Cf. https://www.notion.so/mission-apprentissage/CGU-af1f820ddf3b4facac8a9f365ab5d4a7?pvs=4
> feat(ui): cgu content

- ui/app/politique-confidentialite/components/PolitiqueConfidentialite.tsx
MAJ du contenu de la page politique de confidentialite.
Cf. https://www.notion.so/mission-apprentissage/Protection-des-donn-es-Politique-de-confidentialit-df4860b170ca40199b6c373ac799e7fc?pvs=4
> feat(ui): politique confidentialite

- shared/docs/certification/00_identifiant/identifiant/tip.md
- shared/docs/certification/01_periode_validite/periode_validite.rncp/description.md
- shared/docs/certification/06_continuite/continuite/description.md
- shared/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
- shared/models/certification.model.ts
Correction de quelques coquilles d'orthographe
> fix(ui): orthographe

- .infra/ansible/deploy.yml
Related: https://github.com/mission-apprentissage/infra/pull/53
> feat: upgrade infra

- ui/app/accessibilite/page.tsx
Correction du contenu accessibilité
> fix(ui): ajout du contenu de la page accessibilite

- ui/app/[lang]/explorer/components/CatalogueHeadline.tsx
- ui/app/[lang]/explorer/recherche-offre/page.tsx
- ui/app/i18n/locales/en/explorer.json
- ui/app/i18n/locales/fr/explorer.json
Ajout d'un texte warning pour l'utilisation des données LBA
> feat(ui): ajout warning utilisation données LBA

- ui/components/header/MonCompteQuickAccess.tsx
Ajout du param lang dans les deps du useCallback (warning)
> fix(ui): add lang param to useCallback dependancies

- ui/app/[lang]/explorer/certifications/page.tsx
> fix(ui): titre liste des certifications

- .talismanrc
- server/src/jobs/importer/dares/ccn/dares.ccn.importer.test.ts
- server/src/jobs/importer/dares/ccn/fixtures/article.html
- server/src/jobs/importer/dares/ccn/scraper/dares.ccn.scraper.test.ts
- server/src/jobs/importer/dares/ccn/scraper/dares.ccn.scraper.ts
> fix: dares importer

- sdk/src/external/laBonneAlternance.api.test.ts
- sdk/src/external/laBonneAlternance.api.ts
- server/src/server/routes/job/job.route.test.ts
- server/src/services/apis/lba/lba.api.test.ts
- server/src/services/jobs/job.service.test.ts
- server/src/services/jobs/job.service.ts
https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A805c2bc3-b985-42ea-9088-d8d83d9b3925&selectedIssue=LBA-1501
> breaking-change: lbac 1501: mise à jour du modele adresse lba

- sdk/src/jwt/jwtAuthToken.ts
- server/src/services/apis/lba/lba.api.test.ts
- server/src/services/apis/lba/lba.api.ts
- server/src/services/security/authorisationService.ts
- shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
- shared/src/models/organisation.model.ts
- shared/src/security/permissions.ts
- ui/app/[lang]/admin/organisations/[id]/components/OrganisationView.tsx
- add applications & appointments habilitations
> feat(sdk): update api habilitations

- sdk/src/routes/jobs/job.routes.ts
- server/src/server/routes/certification.route.test.ts
- server/src/server/routes/experimental/sources/acce.routes.test.ts
- server/src/server/routes/geographie.route.test.ts
- server/src/server/routes/job/job.route.test.ts
- server/src/server/routes/job/job.routes.ts
- server/src/server/routes/organismes.routes.test.ts
- server/src/services/security/authenticationService.test.ts
- server/src/services/security/authenticationService.ts
- shared/src/routes/job.routes.ts
> feat: ajout de la route pour postuler à une opportunité d'emploi La bonne alternance

- server/src/services/sentry/sentry.ts
Profiling cost CPU, and due to our current API usage, reducing sample is required to preserve ressources
> feat: reduce sentry profiling rate

- server/src/services/mongodb/mongodbService.ts
Augmentation du nombre de connections à MongoDB pour permettre plus d'opérations en parallel
> feat: increase mongodb pool-size

- docs/developpement/1password.md
- docs/developpement/developpement.md
- docs/developpement/pre-requesites.md
- ui/middleware.ts
Quick update de la doc (fixes & ajout commandes Ubuntu / WSL)
+ Bonus ajout du CDN Redoc aux CSP et du port server
> feat: update documentation

- server/src/services/apis/bcn/bcn.test.ts
- server/src/services/apis/bcn/bcn.ts
https://www.notion.so/mission-apprentissage/Job-d-import-des-donn-es-BCN-v1-3-1530c88032c880a2a4fcdda959f67290
> fix: mise à jour de l'url de l'API BCN

- sdk/src/docs/models/job/offer_read.model.doc.ts
- sdk/src/models/job/job.model.openapi.ts
- shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Correction de la définition OpenAPI pour l'objet Job
Dépends de : https://github.com/mission-apprentissage/api-apprentissage/pull/245
> feat: fix job object

- server/src/server/routes/job/job.routes.ts
WIP (j'aimerais tester en local), fix du PUT avec ajout du contentType JSON au requestInit
> wip: put job content JSON

- server/src/services/apis/acce/acce.test.ts
- server/src/services/apis/acce/acce.ts
Update des URL ACCE + update des tests liés.
J'ai aussi upgrade le timeout du signal d'abort car en local 150ms n'était pas assez long chez moi.
> feat(server): fix ACCE url

- docs/developpement/developpement.md
- package.json
- sdk/package.json
- sdk/src/models/job/job.model.openapi.ts
- server/package.json
- server/src/jobs/importer/npec/scraper/npec.scraper.test.ts
- shared/package.json
- shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
- ui/package.json
- yarn.lock
Update de la définition Open API du **OfferWriteSchema** pour y intégrer le champ _offer.status_ + update des snapshot vitest
> feat: add offer status to open api definition

- sdk/src/client/internal/geographie/geographie.module.test.ts
- sdk/src/docs/models/commune/commune.model.doc.ts
- sdk/src/models/geographie/commune.model.openapi.ts
- sdk/src/models/geographie/commune.model.ts
- sdk/src/utils/zodWithOpenApi.ts
- server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
- server/src/jobs/importer/commune/commune.importer.test.ts
- server/src/jobs/importer/commune/commune.importer.ts
- server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
- server/src/migrations/20241008164612-referentiel-commune.ts
- server/src/migrations/20241010164812-geographie-api.ts
- server/src/migrations/20241017075143-import-communes.ts
- server/src/migrations/20250102153339-commune.ts
- server/src/services/apis/insee/insee.test.ts
- server/src/services/apis/insee/insee.ts
- shared/src/apis/insee.ts
- shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
- shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
- shared/src/models/commune.model.ts
- shared/src/models/fixtures/commune.model.fixture.ts
https://www.notion.so/mission-apprentissage/Construction-du-Mod-le-Communes-Missions-Locales-v1-1-1700c88032c880659ce7ff9d654f76c4
https://www.notion.so/mission-apprentissage/Job-d-import-du-r-f-rentiel-g-ographique-v1-1-1700c88032c88091a1edd336606d5a6f
> feat: ajout des arrondissements et anciennes communes fusionnées

- sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
- sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
- server/src/services/documentation/expectedDocumentationDelta.ts
- server/src/services/security/authenticationService.test.ts
Correction orthographe & labels
Cf. https://docs.google.com/document/d/1VS7rlDvFXiH4YOkBY-WqzVH45XoZ4gFKliUVAsDSkIU/edit?tab=t.0#heading=h.dr9t4y8f51e et https://tableaudebord-apprentissage.atlassian.net/browse/AA-717
> feat: correction des labels / orthographe

- ui/app/[lang]/admin/hooks/useDeleteOrganisation.ts
Le refresh post delete n'était pas forcé
cf https://stackoverflow.com/questions/72391532/next-js-router-push-not-refreshing-the-page
> feat: force refresh post delete organisation

- sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
- sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
- sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
> feat: update wording impératif

- sdk/src/client/internal/geographie/geographie.module.test.ts
- sdk/src/client/internal/geographie/geographie.module.ts
Ajout du querystring sur la liste des missions locales
> fix: add querystring to listMissionLocales

- Dockerfile
Quick fix cf. 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/actions/runs/13651831037/job/38162699015#step:10:560
> fix: docker file syntax warning

- sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
- sdk/src/docs/routes/generateFormationAppointmentLink/generateFormationAppointmentLink.doc.ts
> feat: fix wording & logo

- sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
Correction de texte en doublon + lien md
> feat: fix wordings & url

- sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
Cf : https://tableaudebord-apprentissage.atlassian.net/browse/LBA-2549
> feat: ajout info dépot cfa

- ui/app/[lang]/cgu/components/Cgu.tsx
> fix: wording API Apprentissage

- sdk/src/routes/jobs/job.routes.openapi.ts
- shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Correction sur la doc de la route getJobById
> fix: doc de la route getJobById

- server/src/server/server.ts
Ajout d'une policy CORS pour autoriser data.gouv (pour doc & swagger)
> feat: update CORS policy for data.gouv.fr

- server/src/server/server.ts
Reverts mission-apprentissage/api-apprentissage#389
> Revert "feat: update CORS policy for data.gouv.fr"

- sdk/src/docs/routes/jobsExport/jobsExport.route.doc.ts
https://tableaudebord-apprentissage.atlassian.net/browse/LBA-2962
> fix: add doc detail job export

- ui/app/[lang]/politique-confidentialite/components/PolitiqueConfidentialite.tsx
https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?jql=assignee%20%3D%20712020%3A805c2bc3-b985-42ea-9088-d8d83d9b3925&selectedIssue=LBA-3081
> feat(lbac-3081): mise a jour de la politique de confidentialité
